addons:
  apt:
    packages:
      - libssl-dev

language: python
python:
  - 3.9.13

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - pytest tests/lepor_tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: master

